### ISSUE TITLE
switch datapusher from fork to main release

### ISSUE THREAD

**Issue by ll911** [bcgov/ckanext-bcgov#136]
@gjlawran @kfishwick can we use the main datapusher instead of our fork?
1, check release https://github.com/ckan/datapusher/releases/tag/0.0.8 works
2, push 0.0.8 to PYPI, as 
```python
Collecting datapusher==0.0.8
  Could not find a version that satisfies the requirement datapusher==0.0.8 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.5, 0.0.6)
No matching distribution found for datapusher==0.0.8
```
3, install via PIP and remove our fork

**Comment by gjlawran** [comment]
@kfishwick Data pusher has failed to start in TEST and PROD since our 1.3.1 release. @ll911 thinks this may be due to a code difference between the 2.3.4 branch that we built on and the code used to build the 2.3.4 PyPi package.

I am wondering if we are dealing with any issues associated with Python version dependency.

**Comment by gjlawran** [comment]
@kfishwick our 1.3.1 is based on CKAN 2.3.5 - which conflicts with the DataPusher .
@kfishwick our 1.4 release based on CKAN 2.5.2 - does not conflict with DataPusher 0.7
We are going to sync our DataPusher fork to 0.8 release and deploy to CAD

**Comment by ll911** [comment]
close as completed.

**Comment by gjlawran** [comment]
DataPusher update needs verification in production with 1.4.0.
