### ISSUE TITLE
WMS resource preview with geoview extension not working in CAD and CAT (1.4)

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#138]
WMS previews are working in prod
https://catalogue.data.gov.bc.ca/dataset/schools-k-12-with-francophone-indicators/resource/d62cc90c-d2d9-44f0-892b-b816454941b1

but the same resource as above isn't working in CAT or CAD
https://cad.data.gov.bc.ca/dataset/wms_test/resource/b7ea8058-ea40-424f-9de4-a6f343cdf823

https://cat.data.gov.bc.ca/dataset/wms_test/resource/596de543-8ac9-4265-a399-c287013b97df

This does work in DEMO (ckan-2.5.2 with leaflet plugin+mapquest tiles)
http://demo.ckan.org/dataset/wms-test/resource/110426c5-9272-42f4-9ae2-0142625be62a

We tried recreating the view and that did not work.

**Comment by gjlawran** [comment]
Prod-
https://openmaps.gov.bc.ca/geo/pub/WHSE_WILDLIFE_MANAGEMENT.WAA_TRAPLINE_AREAS_SP/ows?LAYERS=pub%3AWHSE_WILDLIFE_MANAGEMENT.WAA_TRAPLINE_AREAS_SP&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&FORMAT=image%2Fpng&SRS=EPSG%3A3857&BBOX=-13306157.882031,6887893.491875,-13227886.365078,6966165.0088281&WIDTH=256&HEIGHT=256

New - CAT: - is not doing GetMap request
https://openmaps.gov.bc.ca/geo/pub/WHSE_WILDLIFE_MANAGEMENT.WAA_TRAPLINE_AREAS_SP/ows?service=WMS&request=GetCapabilities&LAYERS=pub%3AWHSE_WILDLIFE_MANAGEMENT.WAA_TRAPLINE_AREAS_SP&TRANSPARENT=TRUE&VERSION=1.1.1&STYLES=&FORMAT=image%2Fpng&SRS=EPSG%3A3857&BBOX=-12523442.7125,5009377.085,-11271098.44125,6261721.35625&WIDTH=256&HEIGHT=256

**Comment by kfishwick** [comment]
CKAN updated the demo site with a redeploy of the geoview extension (same version, but newer commit) and it is now broken.

![image](https://cloud.githubusercontent.com/assets/5503136/17408571/9a477168-5a20-11e6-9446-4097cd997341.png)

The problem is that the geoview is failing when it attempts to parse the url parameters.  If you remove the parameters then the call works.

We are looking into a fix either in the bcgov extension or to fork the geoview repo again & apply a fix there.

**Comment by gjlawran** [comment]
Confirmed now working in CAD.

**Comment by kfishwick** [comment]
Just a note, it seems like it was an intentional change in the geoview extension NOT to strip the parameters any more:

https://github.com/ckan/ckanext-geoview/pull/42/commits/2179cc4cf0d89a29fd76d81b0ac950269c8e8114

So we won't be able to push this change back into the core extension.  We may want to look at redefining the resource urls so that getCapabilities is not included as part of the url.
