### ISSUE TITLE
Investigate query and determine how to return all records with an object_name value

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#158]
It is very helpful to find all records based upon the presence or absence of a value in the object_name field - as this is a way to identify which records are in the BC Geographic Warehouse.

**If** this search should find all the records with a populated object_name value
https://catalogue.data.gov.bc.ca/dataset?q=object_name
https://catalogue.data.gov.bc.ca/api/3/action/package_search?q=object_name

these records should be included in the list, but are not:
https://catalogue.data.gov.bc.ca/dataset/bc-ports-and-terminals
https://catalogue.data.gov.bc.ca/dataset/coastal-bc-boat-launches

**Comment by jrods** [comment]
The query needs additional information to search on a specific field. For searching datasets with a set `object_name`, enter something like this into the search field: 
eg. `object_name:["" TO *]`. 
If you want Geographic datasets without an `object_name`, add a dash infront of the field to negate that search option (will also need to restrict the `type` field to `Geographic` because only geographic datasets can have `object_name`): 
eg. `-object_name:["" TO *] AND type:Geographic`.

**Comment by Mbrownshoes** [comment]
working on a table to display on a webpage

**Comment by Mbrownshoes** [comment]
the table to do this is in cat_tools.

**Comment by ll911** [comment]
@gjlawran api call you have for object name should be https://catalogue.data.gov.bc.ca/api/3/action/package_show?id=bc-ports-and-terminals
