### ISSUE TITLE
better error handling

### ISSUE THREAD

**Issue by ll911** [bcgov/ckanext-bcgov#199]
any `ckan.logic` error is displayed as "server error" on web page, this can mislead user or troubleshooting, we need display sth more useful other than "server error"

**Comment by gjlawran** [comment]
Investigate if it would be possible to make this a configurable option in core CKAN.

**Comment by kfishwick** [comment]
Server error handling is default CKAN core implementation, detailed information is sometimes dumped to the log file.  Can we get more information on core changes you would like to see?

Note that when we encounter a known exception we usually display an appropriate error message rather than "internal server error".  So, in some cases if this is not happening we should raise a bug here for that case and handle it specifically.

**Comment by kfishwick** [comment]
Two outcomes after Nov 8 status:
1.  Look at the CKAN issue, and ask at the CKAN meeting if there is any plan to improve this area.
2.  Look at, if we can capture a internal server error and redirect the front end to something nicer (A custom error 500 page basically).

**Comment by LeeZeitz** [comment]
Update:

Ckan documentation says that IRoutes.before_map gets called before the routes map is generated; however, in routing.make_map, the error handler route is generated before calling before_map. This prevents us from being able to connect error actions to our own customised error controller(s). 
We have opened an issue in the core ckan community.

Also, even if we do modify the order of these operations so we are able to handle the errors ourselves, we still need to get the original error code, which is being handled by Pylons, and the response we get from Pylons only contains the internal server error code. We may have to extend something inside Pylons to be able to retrieve the original error code.

**Comment by Khalegh-H3** [comment]
Ckan uses pylons for error handling and when an exception happens ckan
renders whatever it gets as a response from pylons.

Having that said, there is a little room to customize error handling :

a. An error controller must be added to the extension to process and
render pylons response.
b. error_document_template.html must be added to show and customize error page.
c. pylons doesn’t return error details by default.The only way we can
force it to return the error type and error source is to add the
following line to the [DEFAULT] section of the ini file :

show_error_reason = true

d. We can also customize and replace “Internal server error” message
with a more specific message by adding the following  property to the
ini [DEFAULT] section :

error_message = Whatever EDC wants to be shown.

Please note that Pylons in the best case returns the same info that it
adds to the logs when an error happens. For example, I made the
following error locally by trying to print an undefined property’s
value. It throws the following error in the logs :

Error - <type 'exceptions.AttributeError'>: 'dict' object has no
attribute 'test'

And by adding the above attribute to the ini file, I get the following
response in the error page :

    <html>
    <head>
    <title>Server Error</title>

    </head>
    <body>
    <h1>Server Error</h1>
    An internal server error occurred
    &lt;type 'exceptions.AttributeError'&gt; - 'dict' object has no
attribute 'test'
    </body>
    </html>


However, the big issue is that, we cannot map error handling actions
to our controller code. Because, unlike other actions,‘Add dataset’
for example, Ckan creates it’s own error handling routes without
checking plugins routes first. I have already raised [an issue ](https://github.com/ckan/ckan/issues/3328)  in ckan
github indicating this. And the fix appears to be really easy, it
requires only displacing a few lines of code in Ckan config.routes.py
and as long as we have our own ckan fork it should be fine and we can
fix the issue and have a customized error page.

**Comment by kfishwick** [comment]
@Khalegh-H3  can we merge the core change into our forked version?

**Comment by Mbrownshoes** [comment]
Has this fix been made to 1.6?

**Comment by Mbrownshoes** [comment]
@kfishwick has a changed been made to core? What is the status on this?

**Comment by kfishwick** [comment]
Yes it was made to core & we backported it https://github.com/bcgov/ckan/pull/13.
