### ISSUE TITLE
Prepare JS for a Leaflet based selection map that can report the area of the map to the DOM

### ISSUE THREAD

**Issue by gjlawran** [bcgov/ckanext-bcgov#222]
A simple selection map  will allow a user to zoom in and out and pan around - the geographic bounds (DD lat and lng) will be shared with the routine that will make the API call to OFI.

This Leaflet map will be a DIV in ...https://github.com/gjlawran/gdst .

Also the area of the current map size in hectares (ha) needs to be available to the DOM so that the Submit Download button can be activated once the area displayed reaches below a maximum area threshold for a map.

The following JSFiddle - goes part way there. It adds a rectangle whenever the map stops moving (from zooming and panning).

http://jsfiddle.net/ageara/knogpp93/4/

However, the rectangle should not be required. Some other SO resources are also commented into the code.

**Comment by gjlawran** [comment]
@banders  will look at the JS for this issue as he is familiar with Leaflet.

**Comment by Mbrownshoes** [comment]
@banders @jrods the resource id that contains the object names and maximum downloadable area is here:
.../resource/6f370640-fe58-4aa9-832a-f6f615d5a335

**Comment by jrods** [comment]
@Mbrownshoes which env is that resource in, as well, what dataset?

**Comment by banders** [comment]
@jrods is there already a model window that I should add the geographical data selection tool into?  If so, what are the relevant files for that window's UI?  If not, can you advise on where to open the modal window from?

**Comment by jrods** [comment]
@banders the modal window currently only handles managing ofi resources. It gets called in the templates as a ckan resource for the template itself and the js file that drives it 

the modal template: https://github.com/HighwayThree/ckanext-bcgov/blob/ofi_proto/ckanext/bcgov/templates/ofi/ofi_modal.html
the modal js: https://github.com/HighwayThree/ckanext-bcgov/blob/ofi_proto/ckanext/bcgov/fanstatic/ofi/ofi_modal.js

the modal gets rendered like this: https://github.com/HighwayThree/ckanext-bcgov/blob/ofi_proto/ckanext/bcgov/templates/package/new_resource.html#L8-L10

then the button that opens it: https://github.com/HighwayThree/ckanext-bcgov/blob/ofi_proto/ckanext/bcgov/templates/package/new_resource.html#L8-L10

note that the modal window doesn't have automatic resizing on the X-axis, or really anything for resizing easily, so that needs to be done

**Comment by banders** [comment]
@Mbrownshoes any chance we can get the maximum downloadable area resource in json format? (or does CKAN's API have some capability to translate the format for us?)

**Comment by Mbrownshoes** [comment]
@jrods sorry the package id is
d405f40d-f46c-4256-a8f7-d6c42b8e4886
this is in delivery.
@banders the datastore api makes the resource available in json.

**Comment by kfishwick** [comment]
@Mbrownshoes  we actually need that resource to be in prod - all environments should be using the production resource to access the max AOI.

**Comment by banders** [comment]
I have committed the model order window UI to a fork of highway three's bcgov extension (branch: issue_212_mow).  The modal window includes the leaflet map and the "order" button is enabled/disabled based on the selected map area.  The code has stub methods for 1) fetching the maximum downloadable area of the dataset and for 2) placing the actual data order.

@jrods has merged my work back into highway three's repo, and will finish implementing 1) and 2) above as per #212

**Comment by Mbrownshoes** [comment]
@kfishwick I've added the resource to prod and will send the id to @jrods and @banders.

**Comment by Mbrownshoes** [comment]
@banders When ordering a resource too large (in test) to download there is no message indicating that the resource is too large and that you must zoom in to select smaller area. I thought the 'Place Order' button was greyed out, no?
