### ISSUE TITLE
Unable to create OFI resources for geographic dataset in test and dlv

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#292]
1.6.3, the latest update seems to have caused an new error in cad and cat. After adding an object and creating OFI resources when the 'Resource Update Cycle' is selected the following error is displayed in the console
![screen shot 2017-02-28 at 2 18 30 pm](https://cloud.githubusercontent.com/assets/3362533/23437002/5ce8ecf8-fdc1-11e6-86b6-548e861c30de.png)

clicking save then shows this error:
POST https://....../api/ofi/populate_dataset 500 ()

@ll911 @dkelsey

**Comment by Mbrownshoes** [comment]
@jrods @ll911 we are getting the first js error in prod too, however clicking save does create the OFI resource and there isn't the populate_dataset error observed in cad and cat.

**Comment by jrods** [comment]
I remembering running into that js error before, it's not related to OFI. The option selector for 'Resource Update Cycle' references a missing function. I'll have to see why that function is not available on the page. This js error also happens when adding a standard resource.

The POST error however, relates to #293

**Comment by jrods** [comment]
@Mbrownshoes @dkelsey is the saving the ofi resources still a problem? I just tested in cad and it was successful.
