### ISSUE TITLE
Move back to core ckan

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#298]
We would like to move from our extension of ckan https://github.com/bcgov/ckan back to core, which will allow us to upgrade more recent releases. @kfishwick I remember some customization was done (can't remember exactly what) which is why we had to depart from core. Were those changes merged back to core? 
@ll911

**Comment by Mbrownshoes** [comment]
@kfishwick are you able to assign to one of your developers to investigate what would be involved in this?

**Comment by kfishwick** [comment]
Yes, assigned to @jrods.  I believe last time we looked at this, CKAN core was not porting some of the fixes so we were stalled, but we will investigate again.

**Comment by jrods** [comment]
Here is my analysis on upgrading to newer version of ckan. 

First of all, we won't be able to use v2.6 because it doesn't include filesize and mimetype contribution, but it will be included in v2.7. 

There is no set date for v2.7 release yet.

For this task, I used the master branch of ckan core, so there's a couple of issues regarding with installing ckan using pip with the correct dependencies, which should be fixed on release.

This is so far just the web UI, I haven't tested any of the api endpoints.


### core
  - filesize and mimetype (ckan/#3205) will be available in v2.7
  - #287 need to see if we can get the include leaflet in core to newer version
    - a PR should be made asap to make it for v2.7 release


### db
  - using db dumps in newer version of postgres (version 9.2 is the min for ckan), pg_restore seems to have worked
  - Upgrade to v9.5.x worked with the db dumps from test (ckan.20170320.pgdump & datastore.20170320.pgdump)
    - I used this installer for postgres https://www.bigsql.org/postgresql/installers.jsp -> 9.5.6


### solr
  - using solr v6.1.0, seems to work just fine
  - Here are the steps I used in my local vagrant, they are similar to ckan/solr:latest dockerfile
```
SOLR_CORE=ckan

wget -O /tmp/solr-6.1.0.tgz http://archive.apache.org/dist/lucene/solr/6.1.0/solr-6.1.0.tgz
tar -xvf /tmp/solr-6.1.0.tgz -C /apps
chown -R vagrant /apps/solr-6.1.0
ln -s /apps/solr-6.1.0 /apps/solr

## These steps for solr are from ckan's dockerfile for solr
mkdir -p /apps/solr/server/solr/$SOLR_CORE/conf 
mkdir -p /apps/solr/server/solr/$SOLR_CORE/data 

cd /apps/solr/server/solr/$SOLR_CORE/conf 
# Adding Files 
/usr/bin/wget -O solrconfig.xml https://raw.githubusercontent.com/ckan/ckan/master/contrib/docker/solr/solrconfig.xml
/usr/bin/wget -O schema.xml https://raw.githubusercontent.com/ckan/ckan/master/ckan/config/solr/schema.xml
/usr/bin/wget -O currency.xml https://raw.githubusercontent.com/apache/lucene-solr/releases/lucene-solr/6.0.0/solr/server/solr/configsets/basic_configs/conf/currency.xml
/usr/bin/wget -O synonyms.txt https://raw.githubusercontent.com/apache/lucene-solr/releases/lucene-solr/6.0.0/solr/server/solr/configsets/basic_configs/conf/synonyms.txt
/usr/bin/wget -O stopwords.txt https://raw.githubusercontent.com/apache/lucene-solr/releases/lucene-solr/6.0.0/solr/server/solr/configsets/basic_configs/conf/stopwords.txt
/usr/bin/wget -O protwords.txt https://raw.githubusercontent.com/apache/lucene-solr/releases/lucene-solr/6.0.0/solr/server/solr/configsets/basic_configs/conf/protwords.txt
/usr/bin/wget -O elevate.xml https://raw.githubusercontent.com/apache/lucene-solr/releases/lucene-solr/6.0.0/solr/server/solr/configsets/data_driven_schema_configs/conf/elevate.xml

# Create Core.properties 
echo name=$SOLR_CORE > /apps/solr/server/solr/$SOLR_CORE/core.properties
```


### redis
  - Redis is needed for v2.6 and newer
  - Here's the steps I took to install redis in my vagrant
```
wget -O /tmp/redis-3.2.4.tar.gz http://download.redis.io/releases/redis-3.2.4.tar.gz
tar -xzvf /tmp/redis-3.2.4.tar.gz -C /tmp
cd /tmp/redis-3.2.4
make test
make && make install
PORT=6379
CONFIG_FILE=/etc/redis/6379.conf
LOG_FILE=/var/log/redis_6379.log
DATA_DIR=/var/lib/redis/6379
EXECUTABLE=/usr/local/bin/redis-server
echo -e \
  "${PORT}\n${CONFIG_FILE}\n${LOG_FILE}\n${DATA_DIR}\n${EXECUTABLE}\n" | \
./utils/install_server.sh
```


### ckanext-bcgov
  - ckan.lib.base imports should be replaced with ckan.plugins.toolkit
  - in templates, h.googleanalytics_header, deps -> ckanext-googleanalytics
  - in templates, h.disqus_get_forum_name is missing
    - bcgov/templates/header.html:73
    - bcgov/templates/snippets/main-navigation.html:74
    - bcgov/templates/package/snippets/rss_feeds.html:5
  - in templates, no attribute 'ckanext-googleanalytics/googleanalytics_event_tracking.js', can't be fixed until -> ckanext-googleanalytics
    - bcgov/templates/base.html:195
  - when logged in, user option icons (logout, new items) are missing, could be from the PR that was to include a new version of font-awesome
  - when trying to view a dataset, h.comments_block has not been defined
    - bcgov/templates/package/snippets/bcgw_data.html:53
  - when trying to view organization, h.get_action has not been defined, can't be fixed until -> ckanext-hierarchy
  - when trying to view a user, ValidationError: {'rows': [u'Must be a natural number'], 'start': [u'Must be a natural number']}
  - when viewing a resource, if the resource is valid for datastore, 2 data api buttons are present
  - when trying to create a new group, AttributeError: 'EDCOrganizationController' object has no attribute '_get_group_type',
    - ckanext.bcgov.controllers.organization:80
  - when trying to view groups for a dataset, Helper 'get_action' has not been defined,
    - bcgov/templates/package/snippets/info.html:8
  - when trying to go back to the dataset, there was one instance of connection error, HTTPSConnectionPool(host='apps.gov.bc.ca', port=443): Max retries exceeded with url: /pub/dwds-ofi/info/crsTypes, Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'


### ckanext-googleanalytics
  - ckan has removed genshi (legacy templates)


### ckanext-ga-report
  - bad imports, due to pylons-to-flask migration in core


### ckanext-hierarchy
  - the bcgov fork is far behind, will need to look into updating it
  - when trying to view organization, h.get_action has not been defined, ckanext-hierarchy/ckanext/hierarchy/templates/organization/snippets/organization_list.html:35, this is fixed in original repo

**Comment by dkelsey** [comment]
Spoke with @kfishwick 2017-08-15 about this. 
She stated that they have a working Vagrant image running with ckan 2.7.
She stated she expects the work on this to be finished in the next 2 weeks

**Comment by jeff-at-h3** [comment]
Closes #309

**Comment by Mbrownshoes** [comment]
@jrods , this is in delivery, yeah?

**Comment by jrods** [comment]
Yes, CAD is now using ckan 2.7, from the ckan git repo.

I will reassign to Leo

**Comment by jeff-at-h3** [comment]
@dkelsey suggest we move this to 1.8.x if it won't be deployed on 1.7.x

**Comment by jeff-at-h3** [comment]
@ll911 can we get a status update on this issue? Can this be move to Review/QA for testing?

**Comment by dkelsey** [comment]
[status_show](https://cat.data.gov.bc.ca/api/3/action/status_show)
```ckan_version: "2.7.2",```
@ll911 which version of Solr and Postgres is in CAT?

**Comment by dkelsey** [comment]
in PROD status_show:
`"ckan_version": "2.7.2",`
