### ISSUE TITLE
Unable to download a publically available OFI resource, when not logged in. Dlv and Test

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#300]
When not logged in, attempting to download a public resource (cat and cad: /test-1-6-3-geographic-dataset), results in the following error, when the 'Place order' button is clicked.
![screen shot 2017-03-03 at 3 52 46 pm](https://cloud.githubusercontent.com/assets/3362533/23573250/7a907086-0029-11e7-9447-e6646def6387.png)
@ll911

**Comment by Mbrownshoes** [comment]
@jrods have you been able to look at this? we're hoping to get this fixed asap.
@dkelsey

**Comment by jrods** [comment]
I'm currently investigating it, I still haven't found the root cause yet.

**Comment by jrods** [comment]
@Mbrownshoes This issue also happens in the delivery env. The root cause is the public user is actually denied by the file_formats auth check. This issue is similar to #293 , public users are denied by file_formats ( dwds api call -> /info/fileFormats )
I can make a PR to allow for public users to use this call.

**Comment by Mbrownshoes** [comment]
@dkelsey can you please check that this issue is fixed in cad, and check that the OFI is working in general
