### ISSUE TITLE
POW/OFI Integration

### ISSUE THREAD

**Issue by jeff-at-h3** [bcgov/ckanext-bcgov#401]
Replace MOW with POW.

**Comment by jeff-at-h3** [comment]
We need more clarity around requirements and expectations before we can estimate $ and schedule. Reference Dave’s initial design – should Jeff work with Dave on the requirements?
CN> yes, Dave and Terry Lanktree
Dave has completed initial design on gogs. 

Next Steps: evaluate and ensure that we understand and can implement Dave’s prototype (H3)
H3 to submit design options
Some wire-framing should be completed

**Comment by jrods** [comment]
@dkelsey i have your initial code in my env. Atm, I'm just reviewing it and making some cleanup. What are the next steps for this integration?

**Comment by dkelsey** [comment]
I think we said add separate resources as links that launch the POW.
My demo simply had a button for all resource types as well as the usual drop-down button.
By resources I mean SHP, CSV, GoeJSON, and FileGeoDatabase.

**Comment by jrods** [comment]
@dkelsey ok, so I would just be replacing the MOW launcher, with the POW launcher instead? On all ofi resources?

**Comment by dkelsey** [comment]
@jrods correct.

**Comment by jrods** [comment]
Verifying in CAD: go to any OFI dataset and view the resources. Go to the Explore button and select Access/Download to start the POW window. Note, your web browser may so a warning that it requires authorization to open the new window the POW will be in (eg. Firefox).

![screen shot 2018-02-15 at 4 07 27 pm](https://user-images.githubusercontent.com/5874122/36287533-5e5b0684-126a-11e8-8b24-d85705bed312.png)

**Comment by jrods** [comment]
@dkelsey after checking this in cad, the POW isn't getting the format from ckan.

Is there any documention on passing the string of `format` eg. csv? We don't store `formatType` (the number reference for the menu in the POW) within a resource, only the `format` string. The MOW used an API call to get the available `formatTypes` and `formats` but that DWDS API is not available for CAD.

**Comment by jrods** [comment]
@dkelsey after checking this in cad, the POW isn't getting the format from ckan.

Is there any documention on passing the string of `format` eg. csv? We don't store `formatType` (the number reference for the menu in the POW) within a resource, only the `format` string. The MOW used an API call to get the available `formatTypes` and `formats` but that DWDS API is not available for CAD.

**Comment by dkelsey** [comment]
@jrods 
I poked around the API and found  

`dwdspowapi.FormatTypeEnum`

From `https://apps.gov.bc.ca/pub/dwds-ofi/script/pow/dwds-POW-api.js`
```JavaScript
    dwdspowapi.FilterTypeEnum = FilterTypeEnum;
    var FormatTypeEnum = (function () {
        function FormatTypeEnum() {
            this.srcObj = [
                { "formatname": "ArcView Shape", "formatID": 0 },
                { "formatname": "CSV", "formatID": 2 },
                { "formatname": "ESRI File Geodatabase", "formatID": 3 },
                { "formatname": "ESRI File Geodatabase V10", "formatID": 5 },
				{ "formatname": "GeoJSON", "formatID": 6 }];
        }
        FormatTypeEnum.SHAPE = 0;
        FormatTypeEnum.E00 = 1;
        FormatTypeEnum.CSV = 2;
        FormatTypeEnum.GEODATABASE_FILE_V9 = 3;
        FormatTypeEnum.GEODATABASE_FILE_V10 = 5;
		FormatTypeEnum.GEOJSON = 6;
		
        return FormatTypeEnum;
    })();
    dwdspowapi.FormatTypeEnum = FormatTypeEnum;
```

I've asked people at forteconsulting if there is an API to get the values.  

Would it be strange to make a call to download the `dwds-POW-api.js` simply to get the Enum?

**Comment by jrods** [comment]
@dkelsey in our next meeting lets discuss this, and come with a strategy. If we can't give a format name rather than a formatID, we'll probably have to store the formatID as well for OFI resources.

**Comment by dkelsey** [comment]
# Idea:
Load the `dwds-POW-api.js` in the modal window that configures the OFI resources.
With the `dwds-POW-api.js` loaded the enumeration can be queried:


```javascript
var jq = document.createElement('script');
jq.src = "https://apps.gov.bc.ca/pub/dwds-ofi/script/pow/dwds-POW-api.js";
document.getElementsByTagName('head')[0].appendChild(jq);

Opject.keys(dwdspowapi.FormatTypeEnum);
```

![image](https://user-images.githubusercontent.com/3906047/36703881-aa4afc42-1b12-11e8-93ff-b144a223224e.png)

@jrods 
@garrettH3S 
@jeff-at-h3 

Can this be used to get the Format ID when configuring the resources to use the **POW**?

**Comment by jrods** [comment]
@dkelsey possibly, but should check to see if that list is hard-coded (for documentation purpose) or if it's populated when the script is loaded in the page.

**Comment by dkelsey** [comment]
_from a Slack conversation with Jared_


**david [10:37 AM]**
Because the POW-API has no way to query _what is the id associated_  (* **see next comment**)  _with csv_  let's:

* get the associated id from `dwds-POW-api.js` when the record resource is configured, and
* _hard code_ the `id` (in the URL resouse link) so that it is passed to the POW, setting the proper order format.

This way we will continue to have the list of 4 resources ,`CSV`, `File Geodatabase`, `GeoJSON`, `SHP` and the links set the order format type in the POW.

**jrods_h3 [10:49 AM]**
the main problem with this approach is if `dwds-POW-api.js` changes what resource file types are available or if the library changes what the ids are for each file type.
Currently an editor or external script has to update the dataset in ckan to have the appropriate resource types. (edited)

**david [11:00 AM]**
yes good point.
so a better approach would be to get the ID just before loading the POW.
This adds a round trip that would slow the loading of the POW...i'm assuming.
So questions are:
* what's described here would be a less worse approach , and the approach you'd want to take now.
* How long would it take for you or Garrett to do?
* If it takes too long we'd want to hard code it (i'm reluctant to do that) and change it later.
as it is now, you are suggesting that users will have to again, select the format type once the POW has loaded.

right now i'm thinking that would be an ok apprach...as it will force us to eventually fix that.
Colin will suggest, rather than _4 resource links_,  we  have a single link that launches the POW.

**jrods_h3 [11:29 AM]**
[...] A single link would be the best approach, but there will additional work involve with the editing process of OFI resources

**Comment by dkelsey** [comment]
We are all in agreement:
* For the time being we'd do the **Single Link**.

Colin suggested **"BC Geographic Warehouse Custom Download"**

**Comment by dkelsey** [comment]
I asked the vendor that developed the POW, **AGAIN**, if there was an `API` to access the list of resources....and suddenly one materialized :rage:

http://delivery.apps.gov.bc.ca/pub/dwds-ofi/info/fileFormats

I don't think we have enough time/money to use this.

It was suggested that we use the `API` to
*  _just in time, determine available Format Types, and add these as resouces_  **_crazy idea_**.

**Comment by jrods** [comment]
@dkelsey Delivered and verified in cad.

**Comment by mdunhamwilkie** [comment]
@dkelsey can we close this?

**Comment by dkelsey** [comment]
Yes this can be closed.  I created a ticket #603 to capture the comment I made about using the api to get the ID for the format type.

**Comment by cartocrazy** [comment]
Hey David,  it may be in the request you made, and the terminology.  There is no OFI request that gives a list of all resources; resources to Distribution are layers to be downloaded.  What you are looking for, if I understand this correctly, is a list of available File Formats and that does.  This is documented in the swagger document that you have access to under the INFO section.

**Comment by webgismd** [comment]
@cartocrazy can you provide the swagger and or url link the INFO section? 
Thanks!

**Comment by cartocrazy** [comment]
Swagger document will be exposed publicly when we migrate 6.1 to Production.  For now, the team has access to it in test, so I won't post the URL now as most people will not be able to reach it.

**Comment by dkelsey** [comment]
@cartocrazy You have it correct: the list of available File Formats that us needed, specifically the corresponding ID. (we do not want to hard code that value)  This (the ID) is needed so that we can configure "resources" in metadata records, where each resource corresponds to a File Format; these "resources" being links which launch the POW and set the desired format by including the correct corresponding ID for the format.
