### ISSUE TITLE
The search facet for resource format 'other' has the wrong count 

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#478]
## Relates to #386 

# ENV
`CAD` , `CAT` , `PROD`

# TESTCASE

## part 1
* use the API to query for format of `other` and observer the `count`
https://cad.data.gov.bc.ca/api/3/action/resource_search?query=format:other
`1758`
https://cat.data.gov.bc.ca/api/3/action/resource_search?query=format:other
`2573`
https://catalogue.data.gov.bc.ca/api/3/action/resource_search?query=format:other
`2813`

## part 2
* in another window, navigate to the dataset page 
* scroll down and open the **Format** facet and look for `other`

# EXPECTED

* the count and the facet would have the same count.

# ACTUAL

* the facet has the wrong count
  
| **ENV** | **Count** |
|:---------:|:-----------:|
| **CAD** | 154 |
| **CAT** |  4  |
| **PROD** | 22  |

**Comment by hleckenb** [comment]
@dkelsey consider converting "other" to show full metadata for formats, i.e may mean multiple formats, however, this is not much better user wise than actually representing the formats used. Let's take a look at when "other" is applied and determine how to convert to a full list of offered formats.

**Comment by BrandonSharratt** [comment]
So the facet DOESN'T actually have the wrong count. The problem here is that the API being called in the description (action - resource_search) is NOT what is being done by the facet. The facet is doing (action package-search) so the equivalent URL and result here is

http://localhost:5000/api/3/action/package_search?q=res_format:other
https://cad.data.gov.bc.ca/api/3/action/package_search?q=res_format:other
0?

https://cat.data.gov.bc.ca/api/3/action/package_search?q=res_format:other
9

https://catalogue.data.gov.bc.ca/api/3/action/package_search?q=res_format:other
37

Cat and Prod are correct, I don't know what is going on in CAD.

If we are asking for the facet to use the resource search instead of the package search that is doable but it's a a fairly large task at that point (requires us rewriting core CKAN search functionality)

**Comment by hleckenb** [comment]
@dkelsey please provide a user story for this one ... seems that the behaviour of the facet "other" search operates correctly, as in number of datasets. However, if there is a separate need for each tagged resource to be counted for administration purposes, then we need to understand this.

**Comment by SteveChapmanBCDX** [comment]
Reviewed with team, closing as a non-issue.
