### ISSUE TITLE
Evaluate "back to core" CKAN and extensions

### ISSUE THREAD

**Issue by hleckenb** [bcgov/ckanext-bcgov#667]
---
## User Story
**As a developer I want to be able to use the latest core CKAN and extensions as they come available to assert this I need to understand the level of effort, integration requirements, frequency so that I can provide direction to the team on handling core updates.

---
## User Story in a table
| **As A** | **I Want** | **So that** |
|--------|---------|---------|
| _< persona >_ | _< feature >_ | _< reason >_ |

---
## Test Case

# ENV
`PROD`, `CAT`, `CAD`

# TESTCASE
*

# EXPECTED
*

# ACTUAL
*

**Comment by hleckenb** [comment]
@BrandonSharratt please flesh this ticket out further.

**Comment by BrandonSharratt** [comment]
So a partial list of things to consider:

Scheming extension to replace how we are adding fields ourself
Seperating out a POW extension @ll911 suggested moving (at least) this 3 files into a new extension (in ticket #586)
https://github.com/bcgov/ckanext-bcgov/blob/dev/ckanext/bcgov/controllers/ofi.py
https://github.com/bcgov/ckanext-bcgov/tree/dev/ckanext/bcgov/logic/ofi
https://github.com/bcgov/ckanext-bcgov/tree/dev/ckanext/bcgov/templates/ofi
Official Disqus plugin instead of ours

Essentially we want the current ckanext-bcgov extension to be the theme and have all the things that tie the plugins together for us. In the future we would look to isolate this even further by having the UI completely detached from CKAN to modernize it and be able to use CKAN itself as a microservice.

**Comment by SteveChapmanBCDX** [comment]
This issue linked to  ##390.

**Comment by jachurchill** [comment]
I think you said we're good to close this one @SteveChapmanBCDX

**Comment by SteveChapmanBCDX** [comment]
Closing.  This refactoring is complete.  Back to "core" CKAN with following extensions => Scheming, Repeating, Composite.  Removed Disqus, Hierarchy and a bunch of other extensions.  Created new custom extension => bcgov_schema, and sso.
