### ISSUE TITLE
‘Download’ button that sits where the ‘review should be’ does not work

### ISSUE THREAD

**Issue by cbexson** [bcgov/ckanext-bcgov#707]
# ENV
`PROD`

# TESTCASE
* User tried to download the csv and got an error:, "Could not load view: DataProxy returned an error (Data transformation failed. HTTPError: HTTP Error 404: Not Found)".
Dataset: [https://catalogue.data.gov.bc.ca/dataset/fire-incident-locations-historical/resource/219490d7-da49-46b4-a958-1df6aa07f823#]
* The dataset was configured with the old OFI. 

# EXPECTED
* User is taken to the Data Distribution Service

# ACTUAL
* "Could not load view: DataProxy returned an error (Data transformation failed. HTTPError: HTTP Error 404: Not Found)".

**Comment by cbexson** [comment]
Corinne configured the dataset for the new OFI/POW 2019-01-25

**Comment by mdunhamwilkie** [comment]
I believe that the 404 error that Josh was encountering was due to his using a link that he had bookmarked and which has become invalid due to  old MOW links and DWDS links for datasets being replaced with POW links.

The old (presumably bookmarked) link was  
https://catalogue.data.gov.bc.ca/dataset/fire-incident-locations-historical/resource/219490d7-da49-46b4-a958-1df6aa07f823#

The new (POW)  link is:
https://catalogue.data.gov.bc.ca/dataset/fire-incident-locations-historical/resource/6db589c4-e45e-4ae9-a7b5-775cbfec6037 

Note that the resource guid (global unique id) (last part of the URL) has changed.
