### ISSUE TITLE
footer doesn't stick to foot when for short page content

### ISSUE THREAD

**Issue by ll911** [bcgov/ckanext-bcgov#83]
sample see about page
<img width="1179" alt="screen shot 2016-06-22 at 12 14 24 pm" src="https://cloud.githubusercontent.com/assets/11949273/16280096/d8ce981e-3872-11e6-9673-9bf80cd5e467.png">

**Comment by h3devin** [comment]
Fixed in https://github.com/bcgov/ckanext-bcgov/pull/101

**Comment by ll911** [comment]
<img width="1166" alt="screen shot 2016-07-05 at 11 29 00 am" src="https://cloud.githubusercontent.com/assets/11949273/16595384/aeab2666-42a3-11e6-9652-f0f4ae8360f7.png">

**Comment by h3devin** [comment]
That's expected - the footer doesn't currently float or attach itself to the bottom of the browser window.

It looks like that because the footer is appearing right after the content of the page, and since there isn't much in terms of page content you get the footer appearing _before_ the bottom of the browser window.  I added a background color to get rid of the blue -> white transition appearing in the footer (see first comment).

There are ways around this if it's a big issue, but it can get pretty hacky.

**Comment by Mbrownshoes** [comment]
@ll911 is this something for 1.4?

**Comment by ll911** [comment]
@Mbrownshoes footer now does stick o foot, but has another problem as described in the thread. I think we should move this to next sprint.

**Comment by gjlawran** [comment]
Original problem addressed. Is functional. Will review any issues with UI after 2.5 upgrade. Closing.
