### ISSUE TITLE
add Swagger UI console as an extension for API resource preview

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#96]
CITZEDC-806

Estimate the effort to add Swagger UI Console as an extension that allows users to explore APIs that have Swagger definitions files. We would like to know the estimated effort to create an extension that would use the Swagger UI console within CKAN - possibly as an iFrame - to explore APIs that are added as resources. The assumption would be that we would identify the resource as a swagger JSON file format. To see an example of using the Swagger UI Console - look at this record for the BCDC API - http://catalogue.data.gov.bc.ca/dataset/bc-data-catalogue-api and select the second resource called API Console.

**Comment by kfishwick** [comment]
The current approach for this ticket assumes that we will not store the json formatted API spec in the database, so no schema changes are required.

Suggested approach is to add the type "swagger" view to the allowed views (mod to ini file).

Implement the swagger console similar to map preview resource view on the browse resources .

**Comment by gjlawran** [comment]
Banders will fork hwy3 repo. https://github.com/HighwayThree/ckanext-bcgov

**Comment by kfishwick** [comment]
Has this issue been superceded by issue #209?

**Comment by gjlawran** [comment]
This issue is intended to supersede Issue 96.

The purpose of this issue is to add a swagger preview capability to CKAN which will allow "Web Service/API" datasets to show an interactive API console corresponding to the web service's swagger definition file. The API console itself can be constructed from a swagger file using the existing Swagger UI tool.

Suggested Approach:

Develop as a standalone extension.
Embed swagger UI in the dataset view, not in a resource view as was suggested in the discussion around Issue 96.
Other considerations:

Confirm which swagger formats Swagger UI supports (json or yaml or both?). The proposed new extension will have the same limitation.
Confirm where the extension should store/access the dataset's swagger file from.
